version: '3.4'

services:
  booksvc:
    image: ${DOCKER_REGISTRY-}booksvc
    build:
      context: .
      dockerfile: BookSvc/Dockerfile
    volumes:
      - log-volume:/logs

  facade:
    image: ${DOCKER_REGISTRY-}facade
    build:
      context: .
      dockerfile: Facade/Dockerfile
    environment:
      - PERSON_SERVICE=http://personsvc
      - JOKE_SERVICE=http://jokesvc
      - db_connectionstring=host=logdb; database=postgres; user id=postgres; password=mysecretpassword;  #TODO: future enhancement - move to secrets file
    volumes:
      - log-volume:/logs
    depends_on:
      - logdb
    ports:
        - 5009:80


  jokesvc:
    image: ${DOCKER_REGISTRY-}jokesvc
    build:
      context: .
      dockerfile: JokeSvc/Dockerfile
    volumes:
      - log-volume:/logs
    depends_on:
      - logdb

  personsvc:
    image: ${DOCKER_REGISTRY-}personsvc
    build:
      context: .
      dockerfile: PersonSvc/Dockerfile
    volumes:
      - log-volume:/logs
    depends_on:
      - logdb

  playgroundwebfrontend:
    image: ${DOCKER_REGISTRY-}playgroundwebfrontend
    build:
      context: .
      dockerfile: PlaygroundWebFrontend/Dockerfile
    ports:
        - 5000:80
    environment:
        - FacadeService=http://facade
    volumes:
      - log-volume:/logs
    depends_on:
      - logdb

  logdb:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword  #TODO: - move to secrets file
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - log-volume:/logs 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg-data:/var/lib/postgresql/data

volumes:
    log-volume:
    pg-data: